'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Lang = 'en' | 'fr' | 'es';
type Stage = 'lead' | 'qualified' | 'proposal' | 'contract' | 'active' | 'delivered' | 'retainer' | 'lost';
type Priority = 'low' | 'normal' | 'high' | 'urgent';
type Client = { id:string; profile_id:string|null; full_name:string|null; company_name:string|null; email:string|null; phone:string|null; stage:Stage; priority:Priority; estimated_value:number; source:string|null; assigned_to:string|null; next_follow_up_at:string|null; last_contact_at:string|null; tags:string[]; metadata:Record<string,unknown>; created_at:string; updated_at:string };
type Task = { id:string; client_id:string|null; title:string; description:string|null; status:'todo'|'in_progress'|'completed'|'cancelled'; priority:Priority; assigned_to:string|null; due_at:string|null; completed_at:string|null; created_by:string|null; created_at:string; updated_at:string };
type Note = { id:string; client_id:string; body:string; is_pinned:boolean; created_by:string|null; created_at:string; updated_at:string };
type Activity = { id:string; client_id:string; activity_type:string; title:string; description:string|null; metadata:Record<string,unknown>; created_by:string|null; created_at:string };
type Staff = { id:string; full_name:string|null; company_name:string|null; phone:string|null; role:string };
type Props = { staffId:string; staffName:string; initialClients:Client[]; initialTasks:Task[]; initialNotes:Note[]; initialActivity:Activity[]; staffProfiles:Staff[] };

const stages:Stage[]=['lead','qualified','proposal','contract','active','delivered','retainer','lost'];
const priorities:Priority[]=['low','normal','high','urgent'];
const copy={
 en:{workspace:'Internal CRM',title:'Client relationships',subtitle:'Move every opportunity forward, protect client context, and keep the next action visible.',dashboard:'Dashboard',operations:'Intakes',sales:'Sales',clients:'Clients',pipeline:'Pipeline value',openTasks:'Open tasks',followUps:'Follow-ups due',search:'Search clients, companies, email or phone',allStages:'All stages',add:'Add client',name:'Full name',company:'Company',email:'Email',phone:'Phone',source:'Source',stage:'Stage',priority:'Priority',value:'Estimated value',assignee:'Assigned to',followUp:'Next follow-up',save:'Save changes',newTask:'New task',taskTitle:'Task title',description:'Description',due:'Due date',createTask:'Create task',notes:'Private notes',addNote:'Add note',timeline:'Activity timeline',noClient:'Add or select a client to begin.',noTasks:'No tasks for this client.',noNotes:'No private notes yet.',noActivity:'No activity yet.',complete:'Complete',saved:'Client updated.',created:'Client added.',taskCreated:'Task created.',noteCreated:'Note added.',taskCompleted:'Task completed.',busy:'Saving…',newClient:'New client',contact:'Contact',details:'Client details'},
 fr:{workspace:'CRM interne',title:'Relations clients',subtitle:'Faites avancer chaque opportunité, protégez le contexte client et gardez la prochaine action visible.',dashboard:'Tableau de bord',operations:'Dossiers',sales:'Ventes',clients:'Clients',pipeline:'Valeur du pipeline',openTasks:'Tâches ouvertes',followUps:'Relances dues',search:'Rechercher client, entreprise, courriel ou téléphone',allStages:'Toutes les étapes',add:'Ajouter le client',name:'Nom complet',company:'Entreprise',email:'Courriel',phone:'Téléphone',source:'Source',stage:'Étape',priority:'Priorité',value:'Valeur estimée',assignee:'Responsable',followUp:'Prochaine relance',save:'Enregistrer',newTask:'Nouvelle tâche',taskTitle:'Titre de la tâche',description:'Description',due:'Échéance',createTask:'Créer la tâche',notes:'Notes privées',addNote:'Ajouter la note',timeline:'Historique',noClient:'Ajoutez ou sélectionnez un client.',noTasks:'Aucune tâche pour ce client.',noNotes:'Aucune note privée.',noActivity:'Aucune activité.',complete:'Terminer',saved:'Client mis à jour.',created:'Client ajouté.',taskCreated:'Tâche créée.',noteCreated:'Note ajoutée.',taskCompleted:'Tâche terminée.',busy:'Enregistrement…',newClient:'Nouveau client',contact:'Contact',details:'Détails du client'},
 es:{workspace:'CRM interno',title:'Relaciones con clientes',subtitle:'Haz avanzar cada oportunidad, protege el contexto del cliente y mantén visible la próxima acción.',dashboard:'Panel',operations:'Solicitudes',sales:'Ventas',clients:'Clientes',pipeline:'Valor del pipeline',openTasks:'Tareas abiertas',followUps:'Seguimientos vencidos',search:'Buscar cliente, empresa, correo o teléfono',allStages:'Todas las etapas',add:'Agregar cliente',name:'Nombre completo',company:'Empresa',email:'Correo',phone:'Teléfono',source:'Origen',stage:'Etapa',priority:'Prioridad',value:'Valor estimado',assignee:'Asignado a',followUp:'Próximo seguimiento',save:'Guardar cambios',newTask:'Nueva tarea',taskTitle:'Título de la tarea',description:'Descripción',due:'Fecha límite',createTask:'Crear tarea',notes:'Notas privadas',addNote:'Agregar nota',timeline:'Actividad',noClient:'Agrega o selecciona un cliente.',noTasks:'No hay tareas para este cliente.',noNotes:'No hay notas privadas.',noActivity:'No hay actividad.',complete:'Completar',saved:'Cliente actualizado.',created:'Cliente agregado.',taskCreated:'Tarea creada.',noteCreated:'Nota agregada.',taskCompleted:'Tarea completada.',busy:'Guardando…',newClient:'Nuevo cliente',contact:'Contacto',details:'Detalles del cliente'}
};

const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value||0);
const label=(value:string)=>value.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const localInput=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):'';

export default function CrmClient({staffId,staffName,initialClients,initialTasks,initialNotes,initialActivity,staffProfiles}:Props){
 const [lang,setLang]=useState<Lang>('en');
 const [clients,setClients]=useState(initialClients); const [tasks,setTasks]=useState(initialTasks); const [notes,setNotes]=useState(initialNotes); const [activity,setActivity]=useState(initialActivity);
 const [selectedId,setSelectedId]=useState(initialClients[0]?.id||''); const [search,setSearch]=useState(''); const [stageFilter,setStageFilter]=useState('all'); const [showNew,setShowNew]=useState(false); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 useEffect(()=>{const saved=localStorage.getItem('ederito-portal-language') as Lang|null;if(saved&&['en','fr','es'].includes(saved))setLang(saved)},[]);
 const t=copy[lang]; const now=Date.now();
 const filtered=useMemo(()=>clients.filter(c=>{const hay=`${c.full_name||''} ${c.company_name||''} ${c.email||''} ${c.phone||''}`.toLowerCase();return (stageFilter==='all'||c.stage===stageFilter)&&hay.includes(search.toLowerCase())}),[clients,search,stageFilter]);
 const selected=clients.find(c=>c.id===selectedId)||filtered[0]||null;
 const clientTasks=selected?tasks.filter(x=>x.client_id===selected.id):[]; const clientNotes=selected?notes.filter(x=>x.client_id===selected.id):[]; const clientActivity=selected?activity.filter(x=>x.client_id===selected.id):[];
 const openTasks=tasks.filter(x=>!['completed','cancelled'].includes(x.status)).length; const pipeline=clients.filter(x=>!['lost','delivered'].includes(x.stage)).reduce((sum,x)=>sum+Number(x.estimated_value||0),0); const dueFollowUps=clients.filter(x=>x.next_follow_up_at&&new Date(x.next_follow_up_at).getTime()<=now).length;
 function chooseLang(next:Lang){setLang(next);localStorage.setItem('ederito-portal-language',next)}
 async function log(clientId:string,type:string,title:string,description?:string){const supabase=createClient();const {data}=await supabase.from('crm_activity').insert({client_id:clientId,activity_type:type,title,description:description||null,created_by:staffId}).select('*').single();if(data)setActivity(v=>[data as Activity,...v])}
 async function addClient(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice('');const formElement=e.currentTarget;const f=new FormData(formElement);const row={full_name:String(f.get('full_name')||'').trim()||null,company_name:String(f.get('company_name')||'').trim()||null,email:String(f.get('email')||'').trim()||null,phone:String(f.get('phone')||'').trim()||null,source:String(f.get('source')||'').trim()||null,stage:String(f.get('stage')||'lead'),priority:String(f.get('priority')||'normal'),estimated_value:Number(f.get('estimated_value')||0),assigned_to:String(f.get('assigned_to')||'')||null,next_follow_up_at:String(f.get('next_follow_up_at')||'')?new Date(String(f.get('next_follow_up_at'))).toISOString():null};const supabase=createClient();const {data,error}=await supabase.from('crm_clients').insert(row).select('*').single();if(error)setNotice(error.message);else if(data){const client=data as Client;setClients(v=>[client,...v]);setSelectedId(client.id);setShowNew(false);formElement.reset();setNotice(t.created);await log(client.id,'client_created','Client added to CRM',client.full_name||client.company_name||undefined)}setBusy(false)}
 async function updateClient(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);setNotice('');const f=new FormData(e.currentTarget);const patch={full_name:String(f.get('full_name')||'').trim()||null,company_name:String(f.get('company_name')||'').trim()||null,email:String(f.get('email')||'').trim()||null,phone:String(f.get('phone')||'').trim()||null,source:String(f.get('source')||'').trim()||null,stage:String(f.get('stage')),priority:String(f.get('priority')),estimated_value:Number(f.get('estimated_value')||0),assigned_to:String(f.get('assigned_to')||'')||null,next_follow_up_at:String(f.get('next_follow_up_at')||'')?new Date(String(f.get('next_follow_up_at'))).toISOString():null};const supabase=createClient();const {data,error}=await supabase.from('crm_clients').update(patch).eq('id',selected.id).select('*').single();if(error)setNotice(error.message);else if(data){setClients(v=>v.map(x=>x.id===selected.id?data as Client:x));setNotice(t.saved);await log(selected.id,'client_updated','Client record updated',`Stage: ${patch.stage}; priority: ${patch.priority}`)}setBusy(false)}
 async function addTask(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);setNotice('');const formElement=e.currentTarget;const f=new FormData(formElement);const row={client_id:selected.id,title:String(f.get('title')||'').trim(),description:String(f.get('description')||'').trim()||null,priority:String(f.get('priority')||'normal'),assigned_to:String(f.get('assigned_to')||'')||null,due_at:String(f.get('due_at')||'')?new Date(String(f.get('due_at'))).toISOString():null,created_by:staffId};const supabase=createClient();const {data,error}=await supabase.from('crm_tasks').insert(row).select('*').single();if(error)setNotice(error.message);else if(data){setTasks(v=>[data as Task,...v]);formElement.reset();setNotice(t.taskCreated);await log(selected.id,'task_created','Task created',row.title)}setBusy(false)}
 async function completeTask(task:Task){setBusy(true);const completed_at=new Date().toISOString();const supabase=createClient();const {data,error}=await supabase.from('crm_tasks').update({status:'completed',completed_at}).eq('id',task.id).select('*').single();if(error)setNotice(error.message);else if(data){setTasks(v=>v.map(x=>x.id===task.id?data as Task:x));setNotice(t.taskCompleted);if(selected)await log(selected.id,'task_completed','Task completed',task.title)}setBusy(false)}
 async function addNote(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);setNotice('');const formElement=e.currentTarget;const f=new FormData(formElement);const body=String(f.get('body')||'').trim();const supabase=createClient();const {data,error}=await supabase.from('crm_notes').insert({client_id:selected.id,body,is_pinned:f.get('is_pinned')==='on',created_by:staffId}).select('*').single();if(error)setNotice(error.message);else if(data){setNotes(v=>[data as Note,...v]);formElement.reset();setNotice(t.noteCreated);await log(selected.id,'note_created','Private note added')};setBusy(false)}
 return <main className="crm-shell">
  <header className="crm-top"><Link href="/dashboard" className="crm-brand"><img src="https://ederito.com/assets/eder-logo.png" alt="Ederito"/><span>EDERITO</span><em>CRM</em></Link><nav><Link href="/dashboard">{t.dashboard}</Link><Link href="/admin/intakes">{t.operations}</Link><Link href="/admin/sales">{t.sales}</Link><span>{staffName}</span><div className="language-mini">{(['en','fr','es'] as Lang[]).map(x=><button key={x} onClick={()=>chooseLang(x)} className={lang===x?'active':''}>{x.toUpperCase()}</button>)}</div></nav></header>
  <section className="crm-hero"><div><p>{t.workspace}</p><h1>{t.title}.</h1><span>{t.subtitle}</span></div><button onClick={()=>setShowNew(v=>!v)}>＋ {t.newClient}</button></section>
  <section className="crm-metrics"><article><span>{t.clients}</span><strong>{clients.length}</strong></article><article><span>{t.pipeline}</span><strong>{money(pipeline)}</strong></article><article><span>{t.openTasks}</span><strong>{openTasks}</strong></article><article><span>{t.followUps}</span><strong>{dueFollowUps}</strong></article></section>
  {showNew&&<form className="crm-new" onSubmit={addClient}><h2>{t.newClient}</h2><div className="crm-form-grid"><label><span>{t.name}</span><input name="full_name" required/></label><label><span>{t.company}</span><input name="company_name"/></label><label><span>{t.email}</span><input name="email" type="email"/></label><label><span>{t.phone}</span><input name="phone"/></label><label><span>{t.source}</span><input name="source"/></label><label><span>{t.value}</span><input name="estimated_value" type="number" min="0" step="0.01" defaultValue="0"/></label><label><span>{t.stage}</span><select name="stage">{stages.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label><span>{t.priority}</span><select name="priority">{priorities.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label><span>{t.assignee}</span><select name="assigned_to"><option value="">—</option>{staffProfiles.map(x=><option key={x.id} value={x.id}>{x.full_name||x.role}</option>)}</select></label><label><span>{t.followUp}</span><input name="next_follow_up_at" type="datetime-local"/></label></div><button disabled={busy}>{busy?t.busy:t.add}</button></form>}
  <section className="crm-workspace"><aside className="crm-list"><div className="crm-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search}/><select value={stageFilter} onChange={e=>setStageFilter(e.target.value)}><option value="all">{t.allStages}</option>{stages.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div>{filtered.map(c=><button key={c.id} className={selected?.id===c.id?'active':''} onClick={()=>{setSelectedId(c.id);setNotice('')}}><small>{label(c.stage)} · {label(c.priority)}</small><strong>{c.full_name||c.company_name||'Unnamed client'}</strong><span>{c.company_name||c.email||c.phone||'No contact details'}</span><em>{money(c.estimated_value)}</em></button>)}{!filtered.length&&<p>{t.noClient}</p>}</aside>
   <section className="crm-detail">{!selected?<div className="crm-empty">{t.noClient}</div>:<><header className="crm-client-head"><div><p>{t.contact}</p><h2>{selected.full_name||selected.company_name||'Unnamed client'}</h2><span>{selected.company_name||selected.email||selected.phone||'Ederito client'}</span></div><strong>{money(selected.estimated_value)}</strong></header>
    <form className="crm-card" onSubmit={updateClient} key={selected.id}><h3>{t.details}</h3><div className="crm-form-grid"><label><span>{t.name}</span><input name="full_name" defaultValue={selected.full_name||''}/></label><label><span>{t.company}</span><input name="company_name" defaultValue={selected.company_name||''}/></label><label><span>{t.email}</span><input name="email" type="email" defaultValue={selected.email||''}/></label><label><span>{t.phone}</span><input name="phone" defaultValue={selected.phone||''}/></label><label><span>{t.source}</span><input name="source" defaultValue={selected.source||''}/></label><label><span>{t.value}</span><input name="estimated_value" type="number" min="0" step="0.01" defaultValue={selected.estimated_value}/></label><label><span>{t.stage}</span><select name="stage" defaultValue={selected.stage}>{stages.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label><span>{t.priority}</span><select name="priority" defaultValue={selected.priority}>{priorities.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label><span>{t.assignee}</span><select name="assigned_to" defaultValue={selected.assigned_to||''}><option value="">—</option>{staffProfiles.map(x=><option key={x.id} value={x.id}>{x.full_name||x.role}</option>)}</select></label><label><span>{t.followUp}</span><input name="next_follow_up_at" type="datetime-local" defaultValue={localInput(selected.next_follow_up_at)}/></label></div><button disabled={busy}>{busy?t.busy:t.save}</button></form>
    <div className="crm-columns"><section className="crm-card"><h3>{t.newTask}</h3><form onSubmit={addTask} className="crm-stack"><input name="title" required placeholder={t.taskTitle}/><textarea name="description" placeholder={t.description}/><div><select name="priority">{priorities.map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select name="assigned_to"><option value="">{t.assignee}</option>{staffProfiles.map(x=><option key={x.id} value={x.id}>{x.full_name||x.role}</option>)}</select><input name="due_at" type="datetime-local"/></div><button disabled={busy}>{t.createTask}</button></form><div className="crm-records">{clientTasks.map(task=><article key={task.id}><div><small>{label(task.priority)} · {label(task.status)}</small><strong>{task.title}</strong>{task.description&&<p>{task.description}</p>}</div>{task.status!=='completed'&&task.status!=='cancelled'&&<button onClick={()=>completeTask(task)} disabled={busy}>{t.complete}</button>}</article>)}{!clientTasks.length&&<p>{t.noTasks}</p>}</div></section>
     <section className="crm-card"><h3>{t.notes}</h3><form onSubmit={addNote} className="crm-stack"><textarea name="body" required placeholder={t.notes}/><label className="crm-check"><input name="is_pinned" type="checkbox"/> Pin</label><button disabled={busy}>{t.addNote}</button></form><div className="crm-notes">{clientNotes.map(note=><article key={note.id} className={note.is_pinned?'pinned':''}><small>{new Date(note.created_at).toLocaleString()}</small><p>{note.body}</p></article>)}{!clientNotes.length&&<p>{t.noNotes}</p>}</div></section></div>
    <section className="crm-card"><h3>{t.timeline}</h3><div className="crm-timeline">{clientActivity.map(item=><article key={item.id}><i></i><div><small>{new Date(item.created_at).toLocaleString()}</small><strong>{item.title}</strong>{item.description&&<p>{item.description}</p>}</div></article>)}{!clientActivity.length&&<p>{t.noActivity}</p>}</div></section>{notice&&<div className="crm-notice">{notice}</div>}</>}</section>
  </section>
 </main>;
}
