(() => {
  const portal='https://portal.ederito.com';
  const languages=['en','fr','es'];
  const text={en:{login:'Client login',create:'Create account',dashboard:'Dashboard',ai:'AI Studio',project:'New project',site:'Website',signout:'Sign out'},fr:{login:'Connexion client',create:'Créer un compte',dashboard:'Tableau de bord',ai:'Studio IA',project:'Nouveau projet',site:'Site web',signout:'Déconnexion'},es:{login:'Acceso cliente',create:'Crear cuenta',dashboard:'Panel',ai:'Estudio IA',project:'Nuevo proyecto',site:'Sitio web',signout:'Cerrar sesión'}};
  const language=()=>{const saved=localStorage.getItem('ederito-language')||localStorage.getItem('ederito-portal-language');const browser=navigator.language?.slice(0,2).toLowerCase();return languages.includes(saved)?saved:languages.includes(browser)?browser:'en'};
  const persist=(lang)=>{if(!languages.includes(lang))return;localStorage.setItem('ederito-language',lang);localStorage.setItem('ederito-portal-language',lang);document.cookie=`ederito-language=${lang}; Max-Age=31536000; Path=/; Domain=.ederito.com; SameSite=Lax; Secure`};
  const session=async()=>{try{const response=await fetch(`${portal}/api/public/session`,{credentials:'include',cache:'no-store'});return response.ok?await response.json():{authenticated:false}}catch{return{authenticated:false}}};
  function renderDock(data){document.querySelector('.experience-dock')?.remove();const t=text[language()];const dock=document.createElement('nav');dock.className='experience-dock';dock.setAttribute('aria-label','Primary');dock.innerHTML=data.authenticated?`<a href="#top"><b>⌂</b><span>${t.site}</span></a><a href="${portal}/dashboard"><b>▦</b><span>${t.dashboard}</span></a><a href="${portal}/ai-planner"><b>✦</b><span>${t.ai}</span></a><a href="${portal}/start-project"><b>＋</b><span>${t.project}</span></a>`:`<a href="#top"><b>⌂</b><span>${t.site}</span></a><a href="${portal}/login"><b>↗</b><span>${t.login}</span></a><a href="${portal}/login?mode=register"><b>＋</b><span>${t.create}</span></a>`;document.body.appendChild(dock)}
  function renderHeader(data){const nav=document.querySelector('.nav');if(!nav)return;nav.querySelectorAll('[data-portal-login],.nav-account,[data-session-link]').forEach(node=>node.remove());const t=text[language()];if(data.authenticated){const dashboard=document.createElement('a');dashboard.href=`${portal}/dashboard`;dashboard.dataset.sessionLink='dashboard';dashboard.className='nav-account';dashboard.textContent=`${data.firstName||t.dashboard} · ${t.dashboard}`;const signout=document.createElement('a');signout.href=`${portal}/auth/signout?returnTo=${encodeURIComponent('https://ederito.com')}`;signout.dataset.sessionLink='signout';signout.textContent=t.signout;nav.append(dashboard,signout)}else{const login=document.createElement('a');login.href=`${portal}/login`;login.dataset.sessionLink='login';login.textContent=t.login;const create=document.createElement('a');create.href=`${portal}/login?mode=register`;create.dataset.sessionLink='create';create.className='nav-account';create.textContent=t.create;nav.append(login,create)}}
  async function refresh(){persist(language());const data=await session();renderHeader(data);renderDock(data)}
  function harden(){const root=document.documentElement;const body=document.body;const sync=()=>root.style.setProperty('--app-height',`${window.visualViewport?.height||window.innerHeight}px`);const focusIn=e=>{if(e.target?.matches?.('input,textarea,select,[contenteditable="true"]'))body.classList.add('keyboard-open')};const focusOut=()=>setTimeout(()=>{if(!document.activeElement?.matches?.('input,textarea,select,[contenteditable="true"]'))body.classList.remove('keyboard-open')},80);document.addEventListener('focusin',focusIn);document.addEventListener('focusout',focusOut);document.addEventListener('pointerdown',()=>body.classList.add('had-pointer'),{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Tab')body.classList.remove('had-pointer');if(e.key==='Escape')document.activeElement?.blur?.()});window.addEventListener('resize',sync,{passive:true});window.visualViewport?.addEventListener('resize',sync,{passive:true});sync()}
  function init(){document.querySelectorAll('[data-language]').forEach(button=>button.addEventListener('click',()=>{persist(button.dataset.language);setTimeout(refresh,0)}));harden();refresh()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
