(() => {
  const portal='https://portal.ederito.com';
  const languages=['en','fr','es'];
  const text={en:{login:'Client login',create:'Create account',dashboard:'Dashboard',signout:'Sign out',language:'Language'},fr:{login:'Connexion client',create:'Créer un compte',dashboard:'Tableau de bord',signout:'Déconnexion',language:'Langue'},es:{login:'Acceso cliente',create:'Crear cuenta',dashboard:'Panel',signout:'Cerrar sesión',language:'Idioma'}};
  const cookieLanguage=()=>document.cookie.match(/(?:^|; )ederito-language=(en|fr|es)/)?.[1]||'';
  const language=()=>{const shared=cookieLanguage();const saved=localStorage.getItem('ederito-language')||localStorage.getItem('ederito-portal-language');const browser=navigator.language?.slice(0,2).toLowerCase();return languages.includes(shared)?shared:languages.includes(saved)?saved:languages.includes(browser)?browser:'en'};
  const persist=(lang)=>{if(!languages.includes(lang))return;localStorage.setItem('ederito-language',lang);localStorage.setItem('ederito-portal-language',lang);document.cookie=`ederito-language=${lang}; Max-Age=31536000; Path=/; Domain=.ederito.com; SameSite=Lax; Secure`};
  const session=async()=>{try{const response=await fetch(`${portal}/api/public/session`,{credentials:'include',cache:'no-store'});return response.ok?await response.json():{authenticated:false}}catch{return{authenticated:false}}};
  function removeDock(){document.querySelector('.experience-dock')?.remove();if(!document.getElementById('ederito-no-bottom-dock')){const style=document.createElement('style');style.id='ederito-no-bottom-dock';style.textContent='.experience-dock{display:none!important}body{padding-bottom:max(0px,env(safe-area-inset-bottom))!important}';document.head.appendChild(style)}}
  function applySharedLanguage(){const lang=language();persist(lang);const control=document.querySelector(`.lang[data-language="${lang}"]`);if(control&&!control.classList.contains('active'))control.click()}
  function installFooterLanguage(){document.querySelector('.header .language')?.remove();const footer=document.querySelector('.footer');if(!footer||footer.querySelector('.public-footer-language'))return;const style=document.createElement('style');style.textContent='.footer{min-height:auto!important;padding:46px 0 34px!important;grid-template-columns:1fr auto!important;align-items:end!important}.footer>.identity{align-self:start}.footer>p{grid-column:1/-1;margin:0;padding-top:20px;border-top:1px solid rgba(255,255,255,.1)}.footer>div:not(.public-footer-language):not(.footer-legal-links){display:flex;gap:16px}.public-footer-language{display:flex!important;align-items:center;gap:10px;justify-self:end}.public-footer-language label{color:#8f8d87;font-size:12px}.public-footer-language select{min-width:128px;padding:9px 34px 9px 12px;border:1px solid rgba(255,255,255,.14);border-radius:9px;background:#1a1a1d;color:#f3f0e9;font:inherit;font-weight:700}@media(max-width:640px){.footer{grid-template-columns:1fr!important}.public-footer-language{justify-self:stretch;justify-content:space-between}.public-footer-language select{min-width:150px}}';document.head.appendChild(style);const wrap=document.createElement('div');wrap.className='public-footer-language';const lang=language();wrap.innerHTML=`<label for="ederito-footer-language">${text[lang].language}</label><select id="ederito-footer-language" aria-label="${text[lang].language}"><option value="en">English</option><option value="fr">Français</option><option value="es">Español</option></select>`;const select=wrap.querySelector('select');select.value=lang;select.addEventListener('change',()=>{persist(select.value);const button=document.querySelector(`.lang[data-language="${select.value}"]`);button?.click();document.documentElement.lang=select.value;window.location.reload()});footer.appendChild(wrap)}
  function renderHeader(data){const nav=document.querySelector('.nav');if(!nav)return;nav.querySelectorAll('[data-portal-login],.nav-account,[data-session-link]').forEach(node=>node.remove());const t=text[language()];if(data.authenticated){const dashboard=document.createElement('a');dashboard.href=`${portal}/dashboard`;dashboard.dataset.sessionLink='dashboard';dashboard.className='nav-account';dashboard.textContent=`${data.firstName||t.dashboard} · ${t.dashboard}`;const signout=document.createElement('a');signout.href=`${portal}/auth/signout?returnTo=${encodeURIComponent('https://ederito.com')}`;signout.dataset.sessionLink='signout';signout.textContent=t.signout;nav.append(dashboard,signout)}else{const login=document.createElement('a');login.href=`${portal}/login`;login.dataset.sessionLink='login';login.textContent=t.login;const create=document.createElement('a');create.href=`${portal}/login?mode=register`;create.dataset.sessionLink='create';create.className='nav-account';create.textContent=t.create;nav.append(login,create)}}
  async function refresh(){removeDock();applySharedLanguage();installFooterLanguage();const data=await session();renderHeader(data)}
  function harden(){const root=document.documentElement;const body=document.body;const sync=()=>root.style.setProperty('--app-height',`${window.visualViewport?.height||window.innerHeight}px`);const focusIn=e=>{if(e.target?.matches?.('input,textarea,select,[contenteditable="true"]'))body.classList.add('keyboard-open')};const focusOut=()=>setTimeout(()=>{if(!document.activeElement?.matches?.('input,textarea,select,[contenteditable="true"]'))body.classList.remove('keyboard-open')},80);document.addEventListener('focusin',focusIn);document.addEventListener('focusout',focusOut);document.addEventListener('pointerdown',()=>body.classList.add('had-pointer'),{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Tab')body.classList.remove('had-pointer');if(e.key==='Escape')document.activeElement?.blur?.()});window.addEventListener('resize',sync,{passive:true});window.visualViewport?.addEventListener('resize',sync,{passive:true});sync()}
  function init(){document.querySelectorAll('[data-language]').forEach(button=>button.addEventListener('click',()=>{persist(button.dataset.language);setTimeout(refresh,0)}));harden();refresh()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
