(() => {
  const copy={
    en:{intro:'Built for ambitious ideas.',sub:'Websites, apps and digital systems designed from strategy through launch.',projects:'Products shipped',languages:'Languages',support:'Months support',button:'Start a project',title:'What are you building?',desc:'Choose the closest option. We will turn your idea into a focused project brief.',website:'Website',websiteSub:'Business, booking, portfolio or e-commerce',app:'Mobile app',appSub:'iOS, Android or cross-platform product',platform:'Custom platform',platformSub:'Portal, dashboard or internal system',brand:'Brand & launch',brandSub:'Identity, campaign and growth foundation',continue:'Continue to project form',portal:'Client portal',close:'Close project brief'},
    fr:{intro:'Créé pour les idées ambitieuses.',sub:'Sites, applications et systèmes numériques conçus de la stratégie au lancement.',projects:'Produits livrés',languages:'Langues',support:'Mois de support',button:'Démarrer un projet',title:'Que souhaitez-vous créer ?',desc:'Choisissez l’option la plus proche. Nous transformerons votre idée en brief de projet clair.',website:'Site web',websiteSub:'Entreprise, réservation, portfolio ou e-commerce',app:'Application mobile',appSub:'Produit iOS, Android ou multiplateforme',platform:'Plateforme sur mesure',platformSub:'Portail, tableau de bord ou système interne',brand:'Marque et lancement',brandSub:'Identité, campagne et fondation de croissance',continue:'Continuer vers le formulaire',portal:'Portail client',close:'Fermer le brief'},
    es:{intro:'Creado para ideas ambiciosas.',sub:'Sitios, aplicaciones y sistemas digitales diseñados desde la estrategia hasta el lanzamiento.',projects:'Productos lanzados',languages:'Idiomas',support:'Meses de soporte',button:'Iniciar un proyecto',title:'¿Qué quieres crear?',desc:'Elige la opción más cercana. Convertiremos tu idea en un brief de proyecto enfocado.',website:'Sitio web',websiteSub:'Negocio, reservas, portafolio o e-commerce',app:'Aplicación móvil',appSub:'Producto iOS, Android o multiplataforma',platform:'Plataforma personalizada',platformSub:'Portal, panel o sistema interno',brand:'Marca y lanzamiento',brandSub:'Identidad, campaña y base de crecimiento',continue:'Continuar al formulario',portal:'Portal del cliente',close:'Cerrar brief'}
  };
  const lang=()=>document.documentElement.dataset.lang||'en';
  const t=()=>copy[lang()]||copy.en;
  function proof(){if(document.querySelector('.studio-proof'))return;const hero=document.querySelector('.hero');if(!hero)return;const section=document.createElement('section');section.className='studio-proof wrap reveal visible';section.innerHTML=`<div class="studio-proof-intro"><span>EDERITO STUDIO</span><strong>${t().intro}</strong><small>${t().sub}</small></div><div><strong>6+</strong><span>${t().projects}</span></div><div><strong>3</strong><span>${t().languages}</span></div><div><strong>6</strong><span>${t().support}</span></div>`;hero.insertAdjacentElement('afterend',section)}
  function modal(){if(document.querySelector('.studio-brief'))return;const el=document.createElement('div');el.className='studio-brief';el.setAttribute('aria-hidden','true');el.innerHTML=`<div class="studio-brief-panel" role="dialog" aria-modal="true" aria-labelledby="studioBriefTitle"><div class="studio-brief-head"><div><p class="eyebrow">EDERITO STUDIO</p><h2 id="studioBriefTitle">${t().title}</h2><p>${t().desc}</p></div><button class="studio-brief-close" aria-label="${t().close}">×</button></div><div class="studio-brief-grid"><button class="studio-choice" data-service="Website"><b>${t().website}</b><span>${t().websiteSub}</span></button><button class="studio-choice" data-service="Mobile app"><b>${t().app}</b><span>${t().appSub}</span></button><button class="studio-choice" data-service="Custom platform"><b>${t().platform}</b><span>${t().platformSub}</span></button><button class="studio-choice" data-service="Brand and launch"><b>${t().brand}</b><span>${t().brandSub}</span></button></div><div class="studio-brief-actions"><a class="btn btn-gold studio-continue" href="#contact">${t().continue}</a><a class="btn btn-dark" href="https://portal.ederito.com/login">${t().portal}</a></div></div>`;document.body.appendChild(el);const close=()=>{el.classList.remove('open');el.setAttribute('aria-hidden','true');document.body.style.overflow=''};el.querySelector('.studio-brief-close').addEventListener('click',close);el.addEventListener('click',e=>{if(e.target===el)close()});el.querySelectorAll('.studio-choice').forEach(button=>button.addEventListener('click',()=>{el.querySelectorAll('.studio-choice').forEach(x=>x.classList.remove('active'));button.classList.add('active');const select=document.querySelector('#contactForm select[name="service"],#contactForm select');if(select){const option=[...select.options].find(o=>o.textContent.toLowerCase().includes(button.dataset.service.toLowerCase().split(' ')[0]));if(option)select.value=option.value}}));el.querySelector('.studio-continue').addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});return el}
  function command(){if(document.querySelector('.studio-command'))return;const button=document.createElement('button');button.className='studio-command';button.innerHTML=`<span>${t().button}</span><kbd>⌘ K</kbd>`;button.addEventListener('click',open);document.body.appendChild(button);document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}})}
  function open(){const el=modal()||document.querySelector('.studio-brief');el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>el.querySelector('.studio-choice')?.focus(),20)}
  function upgradeCta(){document.querySelectorAll('a[href="#contact"]').forEach((link,index)=>{if(index===0){link.addEventListener('click',e=>{e.preventDefault();open()})}})}
  function init(){proof();modal();command();upgradeCta()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();