'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Proposal={id:string;proposal_number:string;title:string;scope_summary:string;line_items:{description:string;amount_cents:number}[];total_cents:number;currency:string;status:string;language:string;valid_until:string|null;deposit_percent:number;exclusions:string|null;timeline_summary:string|null;payment_schedule:string|null;accepted_at:string|null;contract_id:string|null;invoice_id:string|null;created_at:string};
type Contract={id:string;proposal_id:string|null;contract_number:string;title:string;status:string;language:string;content:string;scope_summary:string|null;amount_cents:number|null;sent_at:string|null;signed_at:string|null;created_at:string};
type Signature={id:string;contract_id:string;signer_name:string;signer_email:string;signature_text:string;signed_at:string};
type Invoice={id:string;proposal_id:string|null;contract_id:string|null;invoice_number:string;status:string;total_cents:number;due_date:string|null;paid_at:string|null;description:string|null;created_at:string};
type Props={userId:string;userEmail:string;proposals:Proposal[];contracts:Contract[];signatures:Signature[];invoices:Invoice[]};

const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
export default function ClientSales({userId,userEmail,proposals:initial,contracts:initialContracts,signatures:initialSignatures,invoices}:Props){
 const [proposals,setProposals]=useState(initial);const [contracts,setContracts]=useState(initialContracts);const [signatures,setSignatures]=useState(initialSignatures);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 async function decide(id:string,accept:boolean){setBusy(true);setNotice('');const supabase=createClient();const fn=accept?'accept_proposal':'decline_proposal';const {data,error}=await supabase.rpc(fn,{p_proposal_id:id,p_client_note:null});if(error)setNotice(error.message);else{setProposals(v=>v.map(p=>p.id===id?{...p,status:accept?'accepted':'declined',accepted_at:accept?new Date().toISOString():p.accepted_at}:p));if(accept&&data){const result=data as {contract_id:string;invoice_id:string};const [{data:c},{data:i}]=await Promise.all([supabase.from('contracts').select('*').eq('id',result.contract_id).single(),supabase.from('invoices').select('*').eq('id',result.invoice_id).single()]);if(c)setContracts(v=>[c as Contract,...v]);if(i)location.reload()}setNotice(accept?'Proposal accepted. Your agreement and deposit invoice are ready.':'Proposal declined. Ederito has been notified.')}setBusy(false)}
 async function sign(e:FormEvent<HTMLFormElement>,contract:Contract){e.preventDefault();setBusy(true);setNotice('');const f=new FormData(e.currentTarget);const name=String(f.get('name')||'').trim();const signature=String(f.get('signature')||'').trim();const supabase=createClient();const consent='I agree that this electronic signature is legally binding and confirms my acceptance of this Ederito service agreement.';const {data,error}=await supabase.from('contract_signatures').insert({contract_id:contract.id,signer_id:userId,signer_name:name,signer_email:userEmail,signature_text:signature,consent_text:consent,user_agent:navigator.userAgent}).select('*').single();if(error)setNotice(error.message);else if(data){await supabase.from('contracts').update({status:'signed',signed_at:new Date().toISOString(),accepted_name:name,accepted_email:userEmail}).eq('id',contract.id);setSignatures(v=>[data as Signature,...v]);setContracts(v=>v.map(c=>c.id===contract.id?{...c,status:'signed',signed_at:new Date().toISOString()}:c));setNotice('Agreement signed successfully.')}setBusy(false)}
 return <main className="client-sales"><header><Link href="/dashboard">← Dashboard</Link><div><strong>EDERITO</strong><span>PROPOSALS & AGREEMENTS</span></div></header><section className="client-sales-hero"><p>YOUR BUSINESS WORKFLOW</p><h1>Review. Accept.<br/>Move forward.</h1><span>No payment is requested until Ederito has reviewed your request and issued a clear proposal.</span></section><section className="client-sales-grid"><div><h2>Proposals</h2>{proposals.map(p=><article className="client-proposal" key={p.id}><header><div><small>{p.proposal_number}</small><h3>{p.title}</h3></div><strong>{money(p.total_cents)}</strong></header><p>{p.scope_summary}</p><dl><div><dt>Timeline</dt><dd>{p.timeline_summary||'Confirmed in the agreement'}</dd></div><div><dt>Deposit</dt><dd>{p.deposit_percent}%</dd></div><div><dt>Valid until</dt><dd>{p.valid_until||'No fixed expiration'}</dd></div><div><dt>Status</dt><dd>{p.status}</dd></div></dl>{p.exclusions&&<div className="sales-box"><strong>Exclusions</strong><p>{p.exclusions}</p></div>}{p.payment_schedule&&<div className="sales-box"><strong>Payment schedule</strong><p>{p.payment_schedule}</p></div>}{p.status==='sent'&&<div className="proposal-actions"><button disabled={busy} onClick={()=>decide(p.id,true)}>Accept proposal</button><button disabled={busy} onClick={()=>decide(p.id,false)}>Decline</button></div>}</article>)}{!proposals.length&&<p>No proposal has been issued yet.</p>}</div><div><h2>Agreements</h2>{contracts.map(c=>{const signed=signatures.some(s=>s.contract_id===c.id);return <article className="client-contract" key={c.id}><small>{c.contract_number}</small><h3>{c.title}</h3><p>{c.scope_summary}</p><div className="contract-content">{c.content}</div>{!signed&&c.status==='sent'&&<form onSubmit={e=>sign(e,c)}><label><span>Full legal name</span><input name="name" required/></label><label><span>Type your name as your signature</span><input name="signature" required/></label><label className="consent"><input type="checkbox" required/><span>I consent to electronic signature and agree to the service agreement.</span></label><button disabled={busy}>Sign agreement</button></form>}{signed&&<div className="signed-mark">✓ Signed</div>}</article>})}{!contracts.length&&<p>No agreement yet.</p>}<h2>Invoices</h2>{invoices.map(i=><article className="client-invoice" key={i.id}><div><small>{i.invoice_number}</small><strong>{i.description||'Ederito invoice'}</strong></div><div><b>{money(i.total_cents)}</b><span>{i.status}{i.due_date?` · Due ${i.due_date}`:''}</span></div></article>)}{!invoices.length&&<p>No invoice yet.</p>}</div></section>{notice&&<div className="client-sales-notice">{notice}</div>}</main>;
}
