'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Lang='en'|'fr'|'es';
type Proposal={id:string;proposal_number:string;title:string;scope_summary:string;line_items:{description:string;amount_cents:number}[];total_cents:number;currency:string;status:string;language:string;valid_until:string|null;deposit_percent:number;exclusions:string|null;timeline_summary:string|null;payment_schedule:string|null;accepted_at:string|null;contract_id:string|null;invoice_id:string|null;created_at:string};
type Contract={id:string;proposal_id:string|null;contract_number:string;title:string;status:string;language:string;content:string;scope_summary:string|null;amount_cents:number|null;sent_at:string|null;signed_at:string|null;created_at:string};
type Signature={id:string;contract_id:string;signer_name:string;signer_email:string;signature_text:string;signed_at:string};
type Invoice={id:string;proposal_id:string|null;contract_id:string|null;invoice_number:string;status:string;total_cents:number;due_date:string|null;paid_at:string|null;description:string|null;created_at:string};
type Props={userId:string;userEmail:string;proposals:Proposal[];contracts:Contract[];signatures:Signature[];invoices:Invoice[]};

const copy={
 en:{dashboard:'Dashboard',section:'PROPOSALS & AGREEMENTS',eyebrow:'YOUR BUSINESS WORKFLOW',title:'Review. Accept. Move forward.',subtitle:'Review proposals, sign agreements, and pay issued invoices from one secure workspace.',proposals:'Proposals',agreements:'Agreements',invoices:'Invoices',timeline:'Timeline',confirmed:'Confirmed in the agreement',deposit:'Deposit',validUntil:'Valid until',noExpiration:'No fixed expiration',status:'Status',exclusions:'Exclusions',paymentSchedule:'Payment schedule',accept:'Accept proposal',decline:'Decline',noProposal:'No proposal has been issued yet.',fullName:'Full legal name',signature:'Type your name as your signature',consent:'I consent to electronic signature and agree to the service agreement.',sign:'Sign agreement',signed:'Signed',noAgreement:'No agreement yet.',invoice:'Ederito invoice',due:'Due',noInvoice:'No invoice yet.',accepted:'Proposal accepted. Your agreement and deposit invoice are ready.',declined:'Proposal declined. Ederito has been notified.',signedSuccess:'Agreement signed successfully.',binding:'I agree that this electronic signature is legally binding and confirms my acceptance of this Ederito service agreement.'},
 fr:{dashboard:'Tableau de bord',section:'PROPOSITIONS ET CONTRATS',eyebrow:'VOTRE PARCOURS COMMERCIAL',title:'Examinez. Acceptez. Avancez.',subtitle:'Examinez les propositions, signez les contrats et payez les factures émises dans un espace sécurisé.',proposals:'Propositions',agreements:'Contrats',invoices:'Factures',timeline:'Calendrier',confirmed:'Confirmé dans le contrat',deposit:'Acompte',validUntil:'Valable jusqu’au',noExpiration:'Aucune date d’expiration fixe',status:'Statut',exclusions:'Exclusions',paymentSchedule:'Calendrier de paiement',accept:'Accepter la proposition',decline:'Refuser',noProposal:'Aucune proposition n’a encore été émise.',fullName:'Nom légal complet',signature:'Saisissez votre nom comme signature',consent:'Je consens à la signature électronique et j’accepte le contrat de service.',sign:'Signer le contrat',signed:'Signé',noAgreement:'Aucun contrat pour le moment.',invoice:'Facture Ederito',due:'Échéance',noInvoice:'Aucune facture pour le moment.',accepted:'Proposition acceptée. Votre contrat et votre facture d’acompte sont prêts.',declined:'Proposition refusée. Ederito a été informé.',signedSuccess:'Contrat signé avec succès.',binding:'J’accepte que cette signature électronique soit juridiquement contraignante et confirme mon acceptation du contrat de service Ederito.'},
 es:{dashboard:'Panel',section:'PROPUESTAS Y ACUERDOS',eyebrow:'TU FLUJO COMERCIAL',title:'Revisa. Acepta. Avanza.',subtitle:'Revisa propuestas, firma acuerdos y paga facturas emitidas desde un espacio seguro.',proposals:'Propuestas',agreements:'Acuerdos',invoices:'Facturas',timeline:'Cronograma',confirmed:'Confirmado en el acuerdo',deposit:'Depósito',validUntil:'Válida hasta',noExpiration:'Sin fecha fija de vencimiento',status:'Estado',exclusions:'Exclusiones',paymentSchedule:'Calendario de pagos',accept:'Aceptar propuesta',decline:'Rechazar',noProposal:'Aún no se ha emitido ninguna propuesta.',fullName:'Nombre legal completo',signature:'Escribe tu nombre como firma',consent:'Acepto la firma electrónica y el acuerdo de servicio.',sign:'Firmar acuerdo',signed:'Firmado',noAgreement:'Aún no hay acuerdos.',invoice:'Factura de Ederito',due:'Vence',noInvoice:'Aún no hay facturas.',accepted:'Propuesta aceptada. Tu acuerdo y factura de depósito están listos.',declined:'Propuesta rechazada. Ederito fue notificado.',signedSuccess:'Acuerdo firmado correctamente.',binding:'Acepto que esta firma electrónica es legalmente vinculante y confirma mi aceptación del acuerdo de servicio de Ederito.'}
} as const;

const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const currentLanguage=():Lang=>{if(typeof window==='undefined')return'en';const value=localStorage.getItem('ederito-portal-language')||localStorage.getItem('ederito-language');return value==='fr'||value==='es'?value:'en'};
const statusLabel=(value:string,lang:Lang)=>{const map:Record<Lang,Record<string,string>>={en:{sent:'Sent',accepted:'Accepted',declined:'Declined',signed:'Signed',draft:'Draft',paid:'Paid',overdue:'Overdue'},fr:{sent:'Envoyée',accepted:'Acceptée',declined:'Refusée',signed:'Signé',draft:'Brouillon',paid:'Payée',overdue:'En retard'},es:{sent:'Enviada',accepted:'Aceptada',declined:'Rechazada',signed:'Firmado',draft:'Borrador',paid:'Pagada',overdue:'Vencida'}};return map[lang][value.toLowerCase()]||value.replace(/_/g,' ')};

export default function ClientSales({userId,userEmail,proposals:initial,contracts:initialContracts,signatures:initialSignatures,invoices}:Props){
 const [lang,setLang]=useState<Lang>('en');const [proposals,setProposals]=useState(initial);const [contracts,setContracts]=useState(initialContracts);const [signatures,setSignatures]=useState(initialSignatures);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{setLang(currentLanguage());const onLanguage=(event:Event)=>{const next=(event as CustomEvent<Lang>).detail;if(next==='en'||next==='fr'||next==='es')setLang(next)};window.addEventListener('ederito:language',onLanguage as EventListener);return()=>window.removeEventListener('ederito:language',onLanguage as EventListener)},[]);
 const t=copy[lang];
 async function decide(id:string,accept:boolean){setBusy(true);setNotice('');const supabase=createClient();const fn=accept?'accept_proposal':'decline_proposal';const {data,error}=await supabase.rpc(fn,{p_proposal_id:id,p_client_note:null});if(error)setNotice(error.message);else{setProposals(v=>v.map(p=>p.id===id?{...p,status:accept?'accepted':'declined',accepted_at:accept?new Date().toISOString():p.accepted_at}:p));if(accept&&data){const result=data as {contract_id:string;invoice_id:string};const [{data:c},{data:i}]=await Promise.all([supabase.from('contracts').select('*').eq('id',result.contract_id).single(),supabase.from('invoices').select('*').eq('id',result.invoice_id).single()]);if(c)setContracts(v=>[c as Contract,...v]);if(i)location.reload()}setNotice(accept?t.accepted:t.declined)}setBusy(false)}
 async function sign(e:FormEvent<HTMLFormElement>,contract:Contract){e.preventDefault();setBusy(true);setNotice('');const f=new FormData(e.currentTarget);const name=String(f.get('name')||'').trim();const signature=String(f.get('signature')||'').trim();const supabase=createClient();const {data,error}=await supabase.from('contract_signatures').insert({contract_id:contract.id,signer_id:userId,signer_name:name,signer_email:userEmail,signature_text:signature,consent_text:t.binding,user_agent:navigator.userAgent}).select('*').single();if(error)setNotice(error.message);else if(data){await supabase.from('contracts').update({status:'signed',signed_at:new Date().toISOString(),accepted_name:name,accepted_email:userEmail}).eq('id',contract.id);setSignatures(v=>[data as Signature,...v]);setContracts(v=>v.map(c=>c.id===contract.id?{...c,status:'signed',signed_at:new Date().toISOString()}:c));setNotice(t.signedSuccess)}setBusy(false)}
 return <main className="client-sales"><header><Link href="/dashboard">← {t.dashboard}</Link><div><strong>EDERITO</strong><span>{t.section}</span></div></header><section className="client-sales-hero"><p>{t.eyebrow}</p><h1>{t.title}</h1><span>{t.subtitle}</span></section><section className="client-sales-grid"><div><h2>{t.proposals}</h2>{proposals.map(p=><article className="client-proposal" key={p.id}><header><div><small>{p.proposal_number}</small><h3>{p.title}</h3></div><strong>{money(p.total_cents)}</strong></header><p>{p.scope_summary}</p><dl><div><dt>{t.timeline}</dt><dd>{p.timeline_summary||t.confirmed}</dd></div><div><dt>{t.deposit}</dt><dd>{p.deposit_percent}%</dd></div><div><dt>{t.validUntil}</dt><dd>{p.valid_until||t.noExpiration}</dd></div><div><dt>{t.status}</dt><dd>{statusLabel(p.status,lang)}</dd></div></dl>{p.exclusions&&<div className="sales-box"><strong>{t.exclusions}</strong><p>{p.exclusions}</p></div>}{p.payment_schedule&&<div className="sales-box"><strong>{t.paymentSchedule}</strong><p>{p.payment_schedule}</p></div>}{p.status==='sent'&&<div className="proposal-actions"><button disabled={busy} onClick={()=>decide(p.id,true)}>{t.accept}</button><button disabled={busy} onClick={()=>decide(p.id,false)}>{t.decline}</button></div>}</article>)}{!proposals.length&&<p>{t.noProposal}</p>}</div><div><h2>{t.agreements}</h2>{contracts.map(c=>{const signed=signatures.some(s=>s.contract_id===c.id);return <article className="client-contract" key={c.id}><small>{c.contract_number}</small><h3>{c.title}</h3><p>{c.scope_summary}</p><div className="contract-content">{c.content}</div>{!signed&&c.status==='sent'&&<form onSubmit={e=>sign(e,c)}><label><span>{t.fullName}</span><input name="name" required/></label><label><span>{t.signature}</span><input name="signature" required/></label><label className="consent"><input type="checkbox" required/><span>{t.consent}</span></label><button disabled={busy}>{t.sign}</button></form>}{signed&&<div className="signed-mark">✓ {t.signed}</div>}</article>})}{!contracts.length&&<p>{t.noAgreement}</p>}<h2>{t.invoices}</h2>{invoices.map(i=><article className="client-invoice" key={i.id}><div><small>{i.invoice_number}</small><strong>{i.description||t.invoice}</strong></div><div><b>{money(i.total_cents)}</b><span>{statusLabel(i.status,lang)}{i.due_date?` · ${t.due} ${i.due_date}`:''}</span></div></article>)}{!invoices.length&&<p>{t.noInvoice}</p>}</div></section>{notice&&<div className="client-sales-notice">{notice}</div>}</main>;
}
