'use client';

import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Lang='en'|'fr'|'es';
type Tab='projects'|'contracts'|'invoices'|'messages'|'support';
type Project={id:string;name:string;status:string;target_launch_date:string|null;free_maintenance_ends_at:string|null};
type Contract={id:string;title:string;status:string;contract_number:string};
type Invoice={id:string;invoice_number:string;status:string;total_cents:number;due_date:string|null};
type Ticket={id:string;subject:string;status:string;priority:string};
type Conversation={id:string;client_id:string;intake_submission_id:string|null;category:string;title:string;status:string;created_at:string;updated_at:string};
type Message={id:string;conversation_id:string;sender_id:string;sender_role:string;body:string|null;created_at:string;read_at:string|null};
type Attachment={id:string;message_id:string;client_id:string;storage_path:string;file_name:string;mime_type:string|null;size_bytes:number|null;created_at:string};
type Props={name:string;userId:string;isStaff:boolean;projects:Project[];contracts:Contract[];invoices:Invoice[];tickets:Ticket[];initialConversations:Conversation[];initialMessages:Message[];initialAttachments:Attachment[]};

const copy={
 en:{workspace:'Private client workspace',welcome:'Welcome',lead:'A clear view of every project, agreement, invoice, message, and support request.',projects:'Projects',contracts:'Contracts',invoices:'Invoices',messages:'Messages',support:'Support',activeProjects:'Active projects',openInvoices:'Open invoices',openTickets:'Open support tickets',noProjects:'No active project yet. Start a request and Ederito will review the scope before issuing a proposal.',noContracts:'No contract has been issued yet.',noInvoices:'No invoices yet.',noTickets:'No support tickets yet.',noMessages:'No messages yet.',status:'Status',target:'Target',due:'Due',createTicket:'Create a support request',subject:'Subject',description:'Describe the issue or request',priority:'Priority',normal:'Normal',high:'High',urgent:'Urgent',submit:'Submit request',created:'Your support request was created.',signOut:'Sign out',startProject:'Start a project',overview:'Client overview',admin:'Operations',nextStep:'Ready for the next move?',nextStepText:'Choose a service, answer only the relevant questions, and receive a reviewed proposal before work begins.',openWorkspace:'Open workspace',secure:'Secure workspace',concierge:'Project concierge',response:'Human review before payment',reply:'Reply to Ederito',attach:'Attach documents or photos',send:'Send reply',sent:'Reply sent.'},
 fr:{workspace:'Espace client privé',welcome:'Bienvenue',lead:'Une vue claire de chaque projet, contrat, facture, message et demande de support.',projects:'Projets',contracts:'Contrats',invoices:'Factures',messages:'Messages',support:'Assistance',activeProjects:'Projets actifs',openInvoices:'Factures ouvertes',openTickets:'Tickets ouverts',noProjects:'Aucun projet actif. Envoyez une demande et Ederito examinera le périmètre avant de proposer une offre.',noContracts:'Aucun contrat n’a encore été émis.',noInvoices:'Aucune facture.',noTickets:'Aucun ticket d’assistance.',noMessages:'Aucun message.',status:'Statut',target:'Date cible',due:'Échéance',createTicket:'Créer une demande de support',subject:'Sujet',description:'Décrivez le problème ou la demande',priority:'Priorité',normal:'Normale',high:'Élevée',urgent:'Urgente',submit:'Envoyer la demande',created:'Votre demande de support a été créée.',signOut:'Déconnexion',startProject:'Démarrer un projet',overview:'Vue client',admin:'Opérations',nextStep:'Prêt pour la prochaine étape ?',nextStepText:'Choisissez un service, répondez seulement aux questions pertinentes et recevez une proposition examinée avant le début du travail.',openWorkspace:'Ouvrir l’espace',secure:'Espace sécurisé',concierge:'Conciergerie projet',response:'Examen humain avant paiement',reply:'Répondre à Ederito',attach:'Joindre des documents ou photos',send:'Envoyer la réponse',sent:'Réponse envoyée.'},
 es:{workspace:'Espacio privado del cliente',welcome:'Bienvenido',lead:'Una vista clara de cada proyecto, contrato, factura, mensaje y solicitud de soporte.',projects:'Proyectos',contracts:'Contratos',invoices:'Facturas',messages:'Mensajes',support:'Soporte',activeProjects:'Proyectos activos',openInvoices:'Facturas abiertas',openTickets:'Tickets abiertos',noProjects:'Aún no hay proyectos activos. Envía una solicitud y Ederito revisará el alcance antes de emitir una propuesta.',noContracts:'Aún no se ha emitido ningún contrato.',noInvoices:'Aún no hay facturas.',noTickets:'Aún no hay tickets de soporte.',noMessages:'Aún no hay mensajes.',status:'Estado',target:'Fecha objetivo',due:'Vence',createTicket:'Crear solicitud de soporte',subject:'Asunto',description:'Describe el problema o la solicitud',priority:'Prioridad',normal:'Normal',high:'Alta',urgent:'Urgente',submit:'Enviar solicitud',created:'Tu solicitud de soporte fue creada.',signOut:'Cerrar sesión',startProject:'Iniciar un proyecto',overview:'Vista del cliente',admin:'Operaciones',nextStep:'¿Listo para el próximo paso?',nextStepText:'Elige un servicio, responde solo las preguntas pertinentes y recibe una propuesta revisada antes de comenzar.',openWorkspace:'Abrir espacio',secure:'Espacio seguro',concierge:'Concierge de proyecto',response:'Revisión humana antes del pago',reply:'Responder a Ederito',attach:'Adjuntar documentos o fotos',send:'Enviar respuesta',sent:'Respuesta enviada.'}
};

export default function DashboardClient({name,userId,isStaff,projects,contracts,invoices,tickets:initialTickets,initialConversations,initialMessages,initialAttachments}:Props){
 const [lang,setLang]=useState<Lang>('en'); const [tab,setTab]=useState<Tab>('projects'); const [tickets,setTickets]=useState(initialTickets); const [message,setMessage]=useState<string|null>(null); const [busy,setBusy]=useState(false);
 const [conversations]=useState(initialConversations); const [messages,setMessages]=useState(initialMessages); const [attachments,setAttachments]=useState(initialAttachments); const [selectedConversation,setSelectedConversation]=useState(initialConversations[0]?.id||''); const [files,setFiles]=useState<File[]>([]);
 useEffect(()=>{const saved=localStorage.getItem('ederito-portal-language') as Lang|null;if(saved&&['en','fr','es'].includes(saved))setLang(saved)},[]);
 const t=copy[lang]; const openInvoices=invoices.filter(x=>x.status!=='paid').length; const openTickets=tickets.filter(x=>!['closed','resolved'].includes(x.status)).length; const tabs:Tab[]=['projects','contracts','invoices','messages','support'];
 function choose(next:Lang){setLang(next);localStorage.setItem('ederito-portal-language',next)}
 async function submitTicket(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage(null);const formElement=event.currentTarget;const form=new FormData(formElement);const supabase=createClient();const {data,error}=await supabase.from('support_tickets').insert({client_id:userId,subject:String(form.get('subject')||'').trim(),description:String(form.get('description')||'').trim(),priority:String(form.get('priority')||'normal'),status:'open'}).select('id,subject,status,priority').single();if(error)setMessage(error.message);else if(data){setTickets(v=>[data,...v]);setMessage(t.created);formElement.reset()}setBusy(false)}
 async function sendReply(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selectedConversation)return;setBusy(true);setMessage(null);const formElement=event.currentTarget;const form=new FormData(formElement);const body=String(form.get('body')||'').trim();if(!body&&!files.length){setBusy(false);return}const supabase=createClient();const {data:msg,error}=await supabase.from('client_messages').insert({conversation_id:selectedConversation,sender_id:userId,sender_role:'client',body:body||null}).select('id,conversation_id,sender_id,sender_role,body,created_at,read_at').single();if(error||!msg){setMessage(error?.message||'Unable to send.');setBusy(false);return}const rows:Attachment[]=[];for(const file of files){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${userId}/${selectedConversation}/${msg.id}-${Date.now()}-${safe}`;const {error:uploadError}=await supabase.storage.from('client-communications').upload(path,file,{contentType:file.type});if(uploadError){setMessage(uploadError.message);continue}const {data:row}=await supabase.from('client_message_attachments').insert({message_id:msg.id,client_id:userId,storage_path:path,file_name:file.name,mime_type:file.type||null,size_bytes:file.size}).select('id,message_id,client_id,storage_path,file_name,mime_type,size_bytes,created_at').single();if(row)rows.push(row as Attachment)}setMessages(v=>[...v,msg as Message]);setAttachments(v=>[...v,...rows]);setFiles([]);formElement.reset();setMessage(t.sent);setBusy(false)}
 async function openAttachment(item:Attachment){const supabase=createClient();const {data}=await supabase.storage.from('client-communications').createSignedUrl(item.storage_path,300);if(data?.signedUrl)window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 const thread=messages.filter(x=>x.conversation_id===selectedConversation);
 return <main className="portal shell dashboard-shell"><header className="topbar dashboard-topbar"><a className="brand" href="/dashboard"><img className="brand-logo" src="https://ederito.com/assets/eder-logo.png" alt="Ederito logo"/><span>EDERITO</span></a><nav className="navlinks dashboard-nav">{tabs.map(item=><button key={item} className={tab===item?'nav-active':''} onClick={()=>setTab(item)}>{t[item]}</button>)}{isStaff&&<a href="/admin/intakes" className="admin-nav-link">{t.admin}</a>}</nav><div className="top-actions"><div className="language-mini">{(['en','fr','es'] as Lang[]).map(x=><button key={x} onClick={()=>choose(x)} className={x===lang?'active':''}>{x.toUpperCase()}</button>)}</div><form action="/auth/signout" method="post"><button className="button secondary">{t.signOut}</button></form></div></header>
 <section className="dashboard-hero"><div className="dashboard-hero-copy"><p className="eyebrow">{t.workspace}</p><h1>{t.welcome},<br/><span>{name}.</span></h1><p>{t.lead}</p><div className="dashboard-hero-actions"><a className="button" href="/start-project">{t.startProject}</a>{isStaff&&<a className="dashboard-link" href="/admin/intakes">{t.admin} <span>↗</span></a>}<button className="dashboard-link" onClick={()=>setTab('projects')}>{t.openWorkspace} <span>↘</span></button></div></div><aside className="concierge-card"><div className="concierge-index">01 / {t.concierge}</div><div><p className="eyebrow">{t.nextStep}</p><h2>{t.response}</h2><p>{t.nextStepText}</p></div><a href="/start-project">{t.startProject}<span>↗</span></a></aside></section>
 <section className="dashboard-ticker"><div><span>{t.secure}</span><i>✦</i><span>{t.projects}</span><i>✦</i><span>{t.contracts}</span><i>✦</i><span>{t.invoices}</span><i>✦</i><span>{t.messages}</span><i>✦</i><span>{t.support}</span></div></section>
 <section className="dashboard-stats"><article><small>01</small><span>{t.activeProjects}</span><strong>{projects.length.toString().padStart(2,'0')}</strong></article><article><small>02</small><span>{t.contracts}</span><strong>{contracts.length.toString().padStart(2,'0')}</strong></article><article><small>03</small><span>{t.openInvoices}</span><strong>{openInvoices.toString().padStart(2,'0')}</strong></article><article><small>04</small><span>{t.messages}</span><strong>{conversations.length.toString().padStart(2,'0')}</strong></article></section>
 <section className="workspace-section"><header className="workspace-heading"><div><p className="eyebrow">{t.overview}</p><h2>{t[tab]}</h2></div><div className="workspace-tabs">{tabs.map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{t[item]}</button>)}</div></header><div className="workspace-panel">
 {tab==='projects'&&<div className="records-list">{projects.length?projects.map(x=><article className="record premium-record" key={x.id}><div><small>{t.projects}</small><strong>{x.name}</strong></div><span>{t.status}: {x.status}</span></article>):<div className="empty premium-empty"><span>01</span><p>{t.noProjects}</p><a className="button" href="/start-project">{t.startProject}</a></div>}</div>}
 {tab==='contracts'&&<div className="records-list">{contracts.length?contracts.map(x=><article className="record premium-record" key={x.id}><div><small>{x.contract_number}</small><strong>{x.title}</strong></div><span>{t.status}: {x.status}</span></article>):<div className="empty premium-empty"><span>02</span><p>{t.noContracts}</p></div>}</div>}
 {tab==='invoices'&&<div className="records-list">{invoices.length?invoices.map(x=><article className="record premium-record" key={x.id}><div><small>{x.invoice_number}</small><strong>${(x.total_cents/100).toFixed(2)}</strong></div><span>{t.status}: {x.status}</span></article>):<div className="empty premium-empty"><span>03</span><p>{t.noInvoices}</p></div>}</div>}
 {tab==='messages'&&<div className="client-message-layout"><aside>{conversations.map(c=><button key={c.id} className={selectedConversation===c.id?'active':''} onClick={()=>setSelectedConversation(c.id)}><strong>{c.title}</strong><span>{c.category} · {c.status}</span></button>)}{!conversations.length&&<p>{t.noMessages}</p>}</aside><section><div className="client-thread">{thread.map(m=><article key={m.id} className={m.sender_role==='client'?'mine':'theirs'}><header><strong>{m.sender_role==='client'?name:'Ederito'}</strong><time>{new Date(m.created_at).toLocaleString()}</time></header>{m.body&&<p>{m.body}</p>}<div>{attachments.filter(a=>a.message_id===m.id).map(a=><button key={a.id} onClick={()=>openAttachment(a)}>{a.mime_type?.startsWith('image/')?'🖼':'📄'} {a.file_name}</button>)}</div></article>)}</div>{selectedConversation&&<form className="client-reply" onSubmit={sendReply}><textarea name="body" placeholder={t.reply}/><label><input type="file" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.txt" onChange={(e:ChangeEvent<HTMLInputElement>)=>setFiles(Array.from(e.target.files||[]))}/><span>{t.attach}</span></label>{files.length>0&&<div>{files.map(f=><small key={`${f.name}-${f.size}`}>{f.name}</small>)}</div>}<button className="button" disabled={busy}>{busy?'…':t.send}</button></form>}</section></div>}
 {tab==='support'&&<div className="support-layout premium-support"><div className="records-list">{tickets.length?tickets.map(x=><article className="record premium-record" key={x.id}><div><small>{x.priority}</small><strong>{x.subject}</strong></div><span>{x.status}</span></article>):<div className="empty premium-empty"><span>05</span><p>{t.noTickets}</p></div>}</div><form className="form support-form premium-support-form" onSubmit={submitTicket}><p className="eyebrow">{t.support}</p><h3>{t.createTicket}</h3><label className="field"><span>{t.subject}</span><input name="subject" required/></label><label className="field"><span>{t.description}</span><textarea name="description" required/></label><label className="field"><span>{t.priority}</span><select name="priority"><option value="normal">{t.normal}</option><option value="high">{t.high}</option><option value="urgent">{t.urgent}</option></select></label><button className="button" disabled={busy}>{busy?'…':t.submit}</button></form></div>}
 {message&&<div className="notice success">{message}</div>}
 </div></section></main>
}
