const SUPABASE_URL='https://yyeabxdzwaidgvlnlzai.supabase.co';
const SUPABASE_KEY='sb_publishable_wqAMVxq4ZKUBiprV9rV25g_e4covZxI';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const languages=['en','fr','es'];
const copy={
  en:{language:'Language',overview:'Overview',projects:'Projects',proposals:'Proposals',billing:'Billing',contracts:'Contracts',files:'Files',messages:'Messages',support:'Support',start:'Start a project',dashboard:'Client Portal',signout:'Sign out',back:'Back to main website'},
  fr:{language:'Langue',overview:'Aperçu',projects:'Projets',proposals:'Propositions',billing:'Facturation',contracts:'Contrats',files:'Fichiers',messages:'Messages',support:'Assistance',start:'Démarrer un projet',dashboard:'Portail client',signout:'Déconnexion',back:'Retour au site principal'},
  es:{language:'Idioma',overview:'Resumen',projects:'Proyectos',proposals:'Propuestas',billing:'Facturación',contracts:'Contratos',files:'Archivos',messages:'Mensajes',support:'Soporte',start:'Iniciar un proyecto',dashboard:'Portal del cliente',signout:'Cerrar sesión',back:'Volver al sitio principal'}
};
const state={mode:'login',user:null,profile:null,data:{projects:[],requests:[],intakes:[],proposals:[],invoices:[],contracts:[],files:[],messages:[],tickets:[],subscriptions:[]}};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const lang=()=>{const saved=localStorage.getItem('ederito-language')||localStorage.getItem('ederito-portal-language');const browser=navigator.language?.slice(0,2).toLowerCase();return languages.includes(saved)?saved:languages.includes(browser)?browser:'en'};
const persistLanguage=value=>{if(!languages.includes(value))return;localStorage.setItem('ederito-language',value);localStorage.setItem('ederito-portal-language',value);document.cookie=`ederito-language=${value}; Max-Age=31536000; Path=/; Domain=.ederito.com; SameSite=Lax; Secure`};
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function money(cents=0,currency='USD'){return new Intl.NumberFormat('en-US',{style:'currency',currency}).format((cents||0)/100)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function item(title,sub,status=''){return `<div class="list-item"><div><strong>${esc(title)}</strong><small>${esc(sub||'')}</small></div>${status?`<span class="badge">${esc(status)}</span>`:''}</div>`}
function list(rows,mapper,empty='Nothing here yet.'){return rows.length?`<div class="list">${rows.map(mapper).join('')}</div>`:`<div class="empty">${esc(empty)}</div>`}
async function loadTable(name,select='*',order='created_at'){const {data,error}=await db.from(name).select(select).order(order,{ascending:false});if(error){console.warn(name,error.message);return[]}return data||[]}

function installPortalStyles(){
  if($('#portal-restored-styles'))return;
  const style=document.createElement('style');style.id='portal-restored-styles';style.textContent=`
    .portal-language{display:grid;gap:7px;margin-top:6px;padding-top:16px;border-top:1px solid var(--line)}
    .portal-language label{font-size:10px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:var(--muted)}
    .portal-language select{width:100%;min-height:42px;padding:0 12px;border:1px solid var(--line);border-radius:10px;background:var(--surface);color:var(--text);font:700 12px Manrope}
    .intake-progress{display:flex;gap:7px;margin:0 0 24px}.intake-progress span{height:3px;flex:1;border-radius:999px;background:var(--surface2)}.intake-progress span.active{background:var(--gold)}
    .intake-section{padding:22px 0;border-top:1px solid var(--line)}.intake-section:first-of-type{border-top:0;padding-top:0}.intake-section h4{margin:0 0 6px;font:800 17px Manrope}.intake-section>p{margin:0 0 18px;color:var(--muted);font-size:12px}
    .intake-checks{display:grid;grid-template-columns:1fr 1fr;gap:10px}.intake-check{display:flex;gap:10px;align-items:flex-start;padding:13px;border:1px solid var(--line);border-radius:11px;background:var(--surface)}.intake-check input{margin-top:3px;accent-color:var(--gold)}
    .intake-certification{display:flex;gap:11px;align-items:flex-start;padding:15px;border:1px solid var(--line);border-radius:12px;background:var(--surface2);font-size:12px}.intake-certification input{margin-top:3px;accent-color:var(--gold)}
    .project-dialog{width:min(820px,calc(100% - 24px));max-height:92vh;overflow:auto}.project-form{padding:32px}.dialog-head{position:sticky;top:-32px;z-index:3;padding:28px 0 20px;background:var(--surface)}
    .request-number{font-family:Manrope;font-size:11px;color:var(--muted)}
    @media(max-width:640px){.intake-checks{grid-template-columns:1fr}.project-form{padding:22px}.dialog-head{top:-22px;padding-top:20px}}
  `;document.head.appendChild(style);
}

function installLanguageControls(){
  const targets=[$('.sidebar-bottom'),$('.auth-shell')].filter(Boolean);
  targets.forEach((target,index)=>{
    if(target.querySelector('.portal-language'))return;
    const wrap=document.createElement('div');wrap.className='portal-language';if(index===1)wrap.classList.add('auth-language');
    wrap.innerHTML=`<label for="portal-language-${index}">${copy[lang()].language}</label><select id="portal-language-${index}"><option value="en">English</option><option value="fr">Français</option><option value="es">Español</option></select>`;
    const select=wrap.querySelector('select');select.value=lang();select.addEventListener('change',()=>{persistLanguage(select.value);window.location.reload()});target.appendChild(wrap);
  });
}

function applyPortalLanguage(){
  const t=copy[lang()];document.documentElement.lang=lang();
  const labels=['overview','projects','proposals','billing','contracts','files','messages','support'];
  $$('.nav-item').forEach((button,index)=>{if(labels[index])button.textContent=t[labels[index]]});
  $$('[data-start-project]').forEach(button=>button.textContent=t.start);
  $('#signOut').textContent=t.signout;
  const back=$('.sidebar-bottom a');if(back)back.textContent=t.back;
  $('.topbar .eyebrow').textContent=t.dashboard.toUpperCase();
}

function buildFullIntake(){
  const form=$('#projectForm');if(!form)return;
  form.innerHTML=`
    <div class="dialog-head"><div><p class="eyebrow">PROJECT INTAKE</p><h3>Start a project</h3><p>Complete the questions below so Ederito Studio can understand the scope before preparing the next step.</p></div><button id="closeProjectDialog" class="icon-button" type="button" aria-label="Close">×</button></div>
    <div class="intake-progress" aria-hidden="true"><span class="active"></span><span class="active"></span><span class="active"></span><span class="active"></span></div>
    <section class="intake-section"><h4>1. Project basics</h4><p>Tell us what you are building and who it is for.</p><div class="form-grid">
      <div class="field"><label for="projectType">Project type</label><select id="projectType" required><option value="">Choose a service</option><option>Business website</option><option>Landing page</option><option>Portfolio website</option><option>Online store</option><option>Booking website</option><option>Mobile application</option><option>Web application or portal</option><option>Branding and UI/UX</option><option>SEO and performance</option><option>AI solution or chatbot</option><option>Hosting, email, DNS or SSL</option><option>Maintenance and support</option><option>LLC formation assistance</option><option>Other</option></select></div>
      <div class="field"><label for="projectCompany">Company or organization</label><input id="projectCompany" autocomplete="organization" placeholder="Business or organization name"></div>
      <div class="field"><label for="currentWebsite">Current website or app</label><input id="currentWebsite" type="url" placeholder="https:// (optional)"></div>
      <div class="field"><label for="launchDate">Preferred launch date</label><input id="launchDate" type="date"></div>
    </div><div class="field"><label for="projectGoals">What are the main goals of this project?</label><textarea id="projectGoals" rows="4" required placeholder="Example: attract customers, accept bookings, sell products, improve credibility, or launch a new service."></textarea></div><div class="field"><label for="targetAudience">Who is your target audience?</label><textarea id="targetAudience" rows="3" required placeholder="Describe the people, customers, or organizations this project should serve."></textarea></div></section>
    <section class="intake-section"><h4>2. Scope and functionality</h4><p>Describe what the finished product needs to include.</p><div class="field"><label for="requiredFeatures">What features do you need?</label><textarea id="requiredFeatures" rows="5" required placeholder="Examples: contact form, payments, booking, accounts, dashboard, messaging, subscriptions, multilingual pages, notifications, analytics."></textarea></div><div class="field"><label for="pagesScreens">Which pages or screens should be included?</label><textarea id="pagesScreens" rows="4" placeholder="List the pages, screens, or major sections you already know you need."></textarea></div><div class="field"><label>Which services or integrations may be needed?</label><div class="intake-checks"><label class="intake-check"><input type="checkbox" name="integrations" value="Online payments"><span>Online payments</span></label><label class="intake-check"><input type="checkbox" name="integrations" value="Booking or scheduling"><span>Booking or scheduling</span></label><label class="intake-check"><input type="checkbox" name="integrations" value="Professional email"><span>Professional email</span></label><label class="intake-check"><input type="checkbox" name="integrations" value="Customer accounts"><span>Customer accounts</span></label><label class="intake-check"><input type="checkbox" name="integrations" value="Social media"><span>Social media</span></label><label class="intake-check"><input type="checkbox" name="integrations" value="Analytics or SEO"><span>Analytics or SEO</span></label></div></div></section>
    <section class="intake-section"><h4>3. Content and visual direction</h4><p>Let us know what materials are already prepared.</p><div class="form-grid"><div class="field"><label for="contentStatus">Is your content ready?</label><select id="contentStatus" required><option value="">Choose one</option><option>Yes, all text and images are ready</option><option>Partially ready</option><option>No, I need assistance</option></select></div><div class="field"><label for="brandStatus">Do you have a logo and brand identity?</label><select id="brandStatus" required><option value="">Choose one</option><option>Yes, complete brand assets</option><option>I only have a logo</option><option>No, I need branding</option></select></div><div class="field"><label for="domainStatus">Domain and hosting status</label><select id="domainStatus"><option value="">Choose one</option><option>I already own a domain and hosting</option><option>I own a domain but need hosting</option><option>I need a domain and hosting</option><option>Not sure</option></select></div><div class="field"><label for="maintenanceNeed">Support after launch</label><select id="maintenanceNeed"><option value="">Choose one</option><option>I want ongoing monthly support</option><option>I only need included post-launch maintenance</option><option>I am not sure yet</option></select></div></div><div class="field"><label for="references">Share websites, apps, or brands you like</label><textarea id="references" rows="3" placeholder="Add links or describe the visual direction you prefer."></textarea></div></section>
    <section class="intake-section"><h4>4. Budget, timeline, and final details</h4><p>These answers help us recommend a realistic scope.</p><div class="form-grid"><div class="field"><label for="projectBudget">Estimated budget</label><select id="projectBudget" required><option value="">Choose a range</option><option>Under $500</option><option>$500–$1,500</option><option>$1,500–$5,000</option><option>$5,000–$10,000</option><option>$10,000+</option><option>I need a recommendation</option></select></div><div class="field"><label for="projectTimeline">Preferred timeline</label><select id="projectTimeline" required><option value="">Choose a timeline</option><option>As soon as possible</option><option>Within 1 month</option><option>Within 2–3 months</option><option>More than 3 months</option><option>Flexible</option></select></div></div><div class="field"><label for="additionalNotes">Anything else we should know?</label><textarea id="additionalNotes" rows="4" placeholder="Include technical requirements, concerns, deadlines, or other context."></textarea></div><label class="intake-certification"><input id="certifiedAccurate" type="checkbox" required><span>I confirm that the information provided is accurate and that I am authorized to submit this request.</span></label></section>
    <div class="dialog-actions"><button id="cancelProject" class="button secondary" type="button">Cancel</button><button id="submitProject" class="button primary" type="submit">Submit request</button></div>`;
}

async function loadData(){if(!state.user)return;const [profile,projects,requests,intakes,proposals,invoices,contracts,files,conversations,tickets,subscriptions]=await Promise.all([
  db.from('profiles').select('*').eq('id',state.user.id).maybeSingle(),loadTable('projects'),loadTable('project_requests'),loadTable('intake_submissions'),loadTable('proposals'),loadTable('invoices'),loadTable('contracts'),loadTable('files'),loadTable('client_conversations'),loadTable('support_tickets'),loadTable('client_subscriptions')]);
  state.profile=profile.data||{};state.data={projects,requests,intakes,proposals,invoices,contracts,files,messages:conversations,tickets,subscriptions};
  const name=state.profile.full_name||state.user.email?.split('@')[0]||'Client';$('#profileName').textContent=name;$('#profileInitial').textContent=name.slice(0,1).toUpperCase();render(currentView())
}
function currentView(){return $('.nav-item.active')?.dataset.view||'overview'}
function intakeTitle(row){return row.responses?.project_type||row.responses?.service||'Project intake'}
function intakeSub(row){return [row.request_number,row.responses?.budget,row.responses?.timeline].filter(Boolean).join(' · ')}
function render(view){
  const t=copy[lang()];$('#pageTitle').textContent=t[view]||view[0].toUpperCase()+view.slice(1);const d=state.data,content=$('#content');
  if(view==='overview'){const due=d.invoices.filter(x=>!['paid','void'].includes(String(x.status).toLowerCase())).reduce((s,x)=>s+(x.total_cents||0),0);content.innerHTML=`<section class="hero-panel"><div class="hero-panel-inner"><div><p class="eyebrow">WELCOME BACK</p><h3>${esc((state.profile?.full_name||'Client').split(' ')[0])}, your work is organized here.</h3><p>Track current projects, complete project requests, review documents, manage billing, and contact Ederito Studio from one place.</p></div><button class="button primary" type="button" data-start-project>${t.start}</button></div></section><div class="stats"><div class="stat"><strong>${d.projects.length}</strong><span>Active projects</span></div><div class="stat"><strong>${d.intakes.length+d.requests.length}</strong><span>Project requests</span></div><div class="stat"><strong>${money(due)}</strong><span>Outstanding</span></div><div class="stat"><strong>${d.messages.length}</strong><span>Conversations</span></div></div><div class="grid-2"><section class="panel"><div class="panel-head"><h3>Projects and requests</h3><button class="button secondary" type="button" data-start-project>New request</button></div>${list([...d.projects.map(x=>({title:x.name,sub:x.description||'Project',status:x.status})),...d.intakes.map(x=>({title:intakeTitle(x),sub:intakeSub(x),status:x.client_visible_status||x.status})),...d.requests.map(x=>({title:x.project_description?.split('\n')[0]?.slice(0,70)||'Project request',sub:[x.budget_range,x.timeline].filter(Boolean).join(' · '),status:x.status}))].slice(0,7),x=>item(x.title,x.sub,x.status),'No projects yet. Start your first request.')}</section><section class="panel"><h3>Action center</h3>${list([...d.proposals.filter(x=>x.status==='sent').map(x=>({t:x.title,s:money(x.total_cents,x.currency),b:'Review proposal'})),...d.invoices.filter(x=>!['paid','void'].includes(String(x.status).toLowerCase())).map(x=>({t:x.invoice_number,s:money(x.total_cents,x.currency),b:x.status}))].slice(0,5),x=>item(x.t,x.s,x.b),'No action needed right now.')}</section></div>`;bindStartButtons();return}
  if(view==='projects')content.innerHTML=`<div class="grid-2"><section class="panel"><div class="panel-head"><h3>Your projects</h3><button class="button primary" type="button" data-start-project>${t.start}</button></div>${list(d.projects,x=>item(x.name,[x.description,x.target_launch_date&&`Target: ${x.target_launch_date}`].filter(Boolean).join(' · '),x.status),'No active projects yet.')}</section><section class="panel"><h3>Project requests</h3>${list([...d.intakes.map(x=>({title:intakeTitle(x),sub:intakeSub(x),status:x.client_visible_status||x.status})),...d.requests.map(x=>({title:x.project_description?.split('\n')[0]?.slice(0,70)||'Project request',sub:[x.budget_range,x.timeline].filter(Boolean).join(' · '),status:x.status}))],x=>item(x.title,x.sub,x.status),'No requests submitted yet.')}</section></div>`;
  if(view==='proposals')content.innerHTML=`<section class="panel"><h3>Proposals</h3>${list(d.proposals,x=>item(x.title,`${x.proposal_number} · ${money(x.total_cents,x.currency)}`,x.status))}</section>`;
  if(view==='billing')content.innerHTML=`<div class="grid-2"><section class="panel"><h3>Invoices</h3>${list(d.invoices,x=>item(x.invoice_number,`${money(x.total_cents,x.currency)}${x.due_date?` · Due ${x.due_date}`:''}`,x.status))}</section><section class="panel"><h3>Subscriptions</h3>${list(d.subscriptions,x=>item(x.subscription_type,`${money(x.amount_cents)} / ${x.billing_interval}`,x.status))}</section></div>`;
  if(view==='contracts')content.innerHTML=`<section class="panel"><h3>Contracts</h3>${list(d.contracts,x=>item(x.title,`${x.contract_number}${x.amount_cents?` · ${money(x.amount_cents,x.currency)}`:''}`,x.status))}</section>`;
  if(view==='files')content.innerHTML=`<section class="panel"><h3>Shared files</h3>${list(d.files,x=>item(x.file_name,x.mime_type||'File',x.visibility))}</section>`;
  if(view==='messages')content.innerHTML=`<section class="panel"><h3>Messages</h3>${list(d.messages,x=>item(x.title,x.category,x.status))}</section>`;
  if(view==='support')content.innerHTML=`<section class="panel"><h3>Support tickets</h3>${list(d.tickets,x=>item(x.subject,x.description,x.status))}</section>`;bindStartButtons()
}
function showApp(session){state.user=session.user;$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');loadData().then(()=>{const params=new URLSearchParams(location.search);if(params.get('service')||params.get('journey'))openProjectDialog()})}
function showAuth(){state.user=null;$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden')}
function openProjectDialog(){if(!state.user)return;$('#projectCompany').value=state.profile?.company_name||'';const service=new URLSearchParams(location.search).get('service');if(service){const option=[...$('#projectType').options].find(x=>x.textContent.toLowerCase().includes(service.toLowerCase().split(' ')[0]));if(option)$('#projectType').value=option.value}$('#projectDialog').showModal()}
function closeProjectDialog(){$('#projectDialog').close();$('#projectForm').reset()}
function bindStartButtons(){$$('[data-start-project]').forEach(btn=>btn.onclick=openProjectDialog)}
function selectedIntegrations(){return $$('input[name="integrations"]:checked').map(input=>input.value)}
function answers(){return {project_type:$('#projectType').value,company_name:$('#projectCompany').value.trim(),current_website:$('#currentWebsite').value.trim(),preferred_launch_date:$('#launchDate').value||null,goals:$('#projectGoals').value.trim(),target_audience:$('#targetAudience').value.trim(),required_features:$('#requiredFeatures').value.trim(),pages_or_screens:$('#pagesScreens').value.trim(),integrations:selectedIntegrations(),content_status:$('#contentStatus').value,brand_status:$('#brandStatus').value,domain_hosting_status:$('#domainStatus').value,post_launch_support:$('#maintenanceNeed').value,references:$('#references').value.trim(),budget:$('#projectBudget').value,timeline:$('#projectTimeline').value,additional_notes:$('#additionalNotes').value.trim(),language:lang()}}

$$('.auth-tab').forEach(btn=>btn.addEventListener('click',()=>{state.mode=btn.dataset.mode;$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===btn));$('#nameField').classList.toggle('hidden',state.mode!=='register');$('#authSubmit').textContent=state.mode==='register'?'Create account':'Sign in';$('#password').autocomplete=state.mode==='register'?'new-password':'current-password'}));
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#email').value.trim(),password=$('#password').value;$('#authSubmit').disabled=true;let result;if(state.mode==='register')result=await db.auth.signUp({email,password,options:{data:{full_name:$('#fullName').value.trim()}}});else result=await db.auth.signInWithPassword({email,password});$('#authSubmit').disabled=false;if(result.error)return toast(result.error.message);if(state.mode==='register'&&!result.data.session)return toast('Check your email to confirm your account.');if(result.data.session)showApp(result.data.session)});
$('#resetPassword').addEventListener('click',async()=>{const email=$('#email').value.trim();if(!email)return toast('Enter your email first.');const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Password reset email sent.')});
$('#signOut').addEventListener('click',async()=>{await db.auth.signOut();showAuth()});$('#refreshData').addEventListener('click',()=>{toast('Refreshing…');loadData()});
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('.sidebar').classList.remove('open');render(btn.dataset.view)}));$('#mobileMenu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();if(!state.user||!$('#certifiedAccurate').checked)return;const submit=$('#submitProject');submit.disabled=true;submit.textContent='Submitting…';const now=new Date().toISOString();const signedName=state.profile?.full_name||state.user.user_metadata?.full_name||state.user.email?.split('@')[0]||'Client';const {error}=await db.from('intake_submissions').insert({client_id:state.user.id,status:'submitted',responses:answers(),quote_required:true,certified_accurate:true,signed_name:signedName,signed_at:now,submitted_at:now,client_visible_status:'Submitted',client_status_message:'Your request has been received and is awaiting review.'});submit.disabled=false;submit.textContent='Submit request';if(error)return toast(error.message);closeProjectDialog();toast('Project request submitted.');history.replaceState({},'',location.pathname);await loadData()});

installPortalStyles();buildFullIntake();installLanguageControls();applyPortalLanguage();bindStartButtons();
$('#closeProjectDialog').addEventListener('click',closeProjectDialog);$('#cancelProject').addEventListener('click',closeProjectDialog);$('#projectDialog').addEventListener('click',e=>{if(e.target===$('#projectDialog'))closeProjectDialog()});
const params=new URLSearchParams(location.search);if(params.get('mode')==='register')$('.auth-tab[data-mode="register"]')?.click();
(async()=>{const {data}=await db.auth.getSession();data.session?showApp(data.session):showAuth();db.auth.onAuthStateChange((_event,session)=>session?showApp(session):showAuth())})();