const SUPABASE_URL='https://yyeabxdzwaidgvlnlzai.supabase.co';
const SUPABASE_KEY='sb_publishable_wqAMVxq4ZKUBiprV9rV25g_e4covZxI';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const state={mode:'login',user:null,profile:null,data:{projects:[],requests:[],proposals:[],invoices:[],contracts:[],files:[],messages:[],tickets:[],subscriptions:[]}};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function money(cents=0,currency='USD'){return new Intl.NumberFormat('en-US',{style:'currency',currency}).format((cents||0)/100)}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function item(title,sub,status=''){return `<div class="list-item"><div><strong>${esc(title)}</strong><small>${esc(sub||'')}</small></div>${status?`<span class="badge">${esc(status)}</span>`:''}</div>`}
function list(rows,mapper,empty='Nothing here yet.'){return rows.length?`<div class="list">${rows.map(mapper).join('')}</div>`:`<div class="empty">${esc(empty)}</div>`}
async function loadTable(name,select='*',order='created_at'){const {data,error}=await db.from(name).select(select).order(order,{ascending:false});if(error){console.warn(name,error.message);return[]}return data||[]}
async function loadData(){if(!state.user)return;const [profile,projects,requests,proposals,invoices,contracts,files,conversations,tickets,subscriptions]=await Promise.all([
 db.from('profiles').select('*').eq('id',state.user.id).maybeSingle(),loadTable('projects'),loadTable('project_requests'),loadTable('proposals'),loadTable('invoices'),loadTable('contracts'),loadTable('files'),loadTable('client_conversations'),loadTable('support_tickets'),loadTable('client_subscriptions')]);
state.profile=profile.data||{};state.data={projects,requests,proposals,invoices,contracts,files,messages:conversations,tickets,subscriptions};
const name=state.profile.full_name||state.user.email?.split('@')[0]||'Client';$('#profileName').textContent=name;$('#profileInitial').textContent=name.slice(0,1).toUpperCase();render(currentView())}
function currentView(){return $('.nav-item.active')?.dataset.view||'overview'}
function render(view){$('#pageTitle').textContent=view[0].toUpperCase()+view.slice(1);const d=state.data;const content=$('#content');if(view==='overview'){const due=d.invoices.filter(x=>!['paid','void'].includes(String(x.status).toLowerCase())).reduce((s,x)=>s+(x.total_cents||0),0);content.innerHTML=`<section class="hero-panel"><div class="hero-panel-inner"><div><p class="eyebrow">WELCOME BACK</p><h3>${esc((state.profile?.full_name||'Client').split(' ')[0])}, your work is organized here.</h3><p>Track current projects, review documents, manage billing, and contact Ederito Studio from one place.</p></div><button class="button primary" type="button" data-start-project>Start a project</button></div></section><div class="stats"><div class="stat"><strong>${d.projects.length}</strong><span>Active projects</span></div><div class="stat"><strong>${d.requests.length}</strong><span>Project requests</span></div><div class="stat"><strong>${money(due)}</strong><span>Outstanding</span></div><div class="stat"><strong>${d.messages.length}</strong><span>Conversations</span></div></div><div class="grid-2"><section class="panel"><div class="panel-head"><h3>Projects and requests</h3><button class="button secondary" type="button" data-start-project>New request</button></div>${list([...d.projects.map(x=>({title:x.name,sub:x.description||'Project',status:x.status})),...d.requests.map(x=>({title:x.project_description?.split('\n')[0]?.slice(0,70)||'Project request',sub:[x.budget_range,x.timeline].filter(Boolean).join(' · '),status:x.status}))].slice(0,6),x=>item(x.title,x.sub,x.status),'No projects yet. Start your first request.')}</section><section class="panel"><h3>Action center</h3>${list([...d.proposals.filter(x=>x.status==='sent').map(x=>({t:x.title,s:money(x.total_cents,x.currency),b:'Review proposal'})),...d.invoices.filter(x=>!['paid','void'].includes(String(x.status).toLowerCase())).map(x=>({t:x.invoice_number,s:money(x.total_cents,x.currency),b:x.status}))].slice(0,5),x=>item(x.t,x.s,x.b),'No action needed right now.')}</section></div>`;bindStartButtons();return}
if(view==='projects')content.innerHTML=`<div class="grid-2"><section class="panel"><div class="panel-head"><h3>Your projects</h3><button class="button primary" type="button" data-start-project>Start a project</button></div>${list(d.projects,x=>item(x.name,[x.description,x.target_launch_date&&`Target: ${x.target_launch_date}`].filter(Boolean).join(' · '),x.status),'No active projects yet.')}</section><section class="panel"><h3>Project requests</h3>${list(d.requests,x=>item(x.project_description?.split('\n')[0]?.slice(0,70)||'Project request',[x.budget_range,x.timeline].filter(Boolean).join(' · '),x.status),'No requests submitted yet.')}</section></div>`;
if(view==='proposals')content.innerHTML=`<section class="panel"><h3>Proposals</h3>${list(d.proposals,x=>item(x.title,`${x.proposal_number} · ${money(x.total_cents,x.currency)}`,x.status))}</section>`;
if(view==='billing')content.innerHTML=`<div class="grid-2"><section class="panel"><h3>Invoices</h3>${list(d.invoices,x=>item(x.invoice_number,`${money(x.total_cents,x.currency)}${x.due_date?` · Due ${x.due_date}`:''}`,x.status))}</section><section class="panel"><h3>Subscriptions</h3>${list(d.subscriptions,x=>item(x.subscription_type,`${money(x.amount_cents)} / ${x.billing_interval}`,x.status))}</section></div>`;
if(view==='contracts')content.innerHTML=`<section class="panel"><h3>Contracts</h3>${list(d.contracts,x=>item(x.title,`${x.contract_number}${x.amount_cents?` · ${money(x.amount_cents,x.currency)}`:''}`,x.status))}</section>`;
if(view==='files')content.innerHTML=`<section class="panel"><h3>Shared files</h3>${list(d.files,x=>item(x.file_name,x.mime_type||'File',x.visibility))}</section>`;
if(view==='messages')content.innerHTML=`<section class="panel"><h3>Messages</h3>${list(d.messages,x=>item(x.title,x.category,x.status))}</section>`;
if(view==='support')content.innerHTML=`<section class="panel"><h3>Support tickets</h3>${list(d.tickets,x=>item(x.subject,x.description,x.status))}</section>`;bindStartButtons()}
function showApp(session){state.user=session.user;$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');loadData()}
function showAuth(){state.user=null;$('#appView').classList.add('hidden');$('#authView').classList.remove('hidden')}
function openProjectDialog(){if(!state.user)return;$('#projectCompany').value=state.profile?.company_name||'';$('#projectDialog').showModal()}
function closeProjectDialog(){$('#projectDialog').close();$('#projectForm').reset()}
function bindStartButtons(){$$('[data-start-project]').forEach(btn=>{btn.onclick=openProjectDialog})}
$$('.auth-tab').forEach(btn=>btn.addEventListener('click',()=>{state.mode=btn.dataset.mode;$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===btn));$('#nameField').classList.toggle('hidden',state.mode!=='register');$('#authSubmit').textContent=state.mode==='register'?'Create account':'Sign in';$('#password').autocomplete=state.mode==='register'?'new-password':'current-password'}));
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#email').value.trim(),password=$('#password').value;$('#authSubmit').disabled=true;let result;if(state.mode==='register')result=await db.auth.signUp({email,password,options:{data:{full_name:$('#fullName').value.trim()}}});else result=await db.auth.signInWithPassword({email,password});$('#authSubmit').disabled=false;if(result.error)return toast(result.error.message);if(state.mode==='register'&&!result.data.session)return toast('Check your email to confirm your account.');if(result.data.session)showApp(result.data.session)});
$('#resetPassword').addEventListener('click',async()=>{const email=$('#email').value.trim();if(!email)return toast('Enter your email first.');const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Password reset email sent.')});
$('#signOut').addEventListener('click',async()=>{await db.auth.signOut();showAuth()});
$('#refreshData').addEventListener('click',()=>{toast('Refreshing…');loadData()});
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('.sidebar').classList.remove('open');render(btn.dataset.view)}));
$('#mobileMenu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));
$('#closeProjectDialog').addEventListener('click',closeProjectDialog);$('#cancelProject').addEventListener('click',closeProjectDialog);$('#projectDialog').addEventListener('click',e=>{if(e.target===$('#projectDialog'))closeProjectDialog()});
$('#projectForm').addEventListener('submit',async e=>{e.preventDefault();if(!state.user)return;const type=$('#projectType').value.trim(),description=$('#projectDescription').value.trim();if(!type||!description)return;const submit=$('#submitProject');submit.disabled=true;submit.textContent='Submitting…';const contactName=state.profile?.full_name||state.user.user_metadata?.full_name||state.user.email?.split('@')[0]||'Client';const {error}=await db.from('project_requests').insert({client_id:state.user.id,contact_name:contactName,contact_email:state.user.email,company_name:$('#projectCompany').value.trim()||null,budget_range:$('#projectBudget').value||null,timeline:$('#projectTimeline').value||null,project_description:`${type}\n${description}`});submit.disabled=false;submit.textContent='Submit request';if(error)return toast(error.message);closeProjectDialog();toast('Project request submitted.');await loadData()});
bindStartButtons();
(async()=>{const {data}=await db.auth.getSession();data.session?showApp(data.session):showAuth();db.auth.onAuthStateChange((_event,session)=>session?showApp(session):showAuth())})();